plugins:
  - serverless-offline

service: serverless-rest-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.15

functions:
  currentTime:
    handler: handler.helloWorld
    events:
      - http:
          path: /hello-world
          method: post